### ISSUE TITLE
Write remarks when you manually stop the timer

### ISSUE THREAD

**Issue by ardcarvalho** [caiomts/timerdo#7]
The "any remark?" question is avaiable when you set your working time, but not when you manually stop the timer. The only question after the command "stop" is if the task is done. Why not adding this question?

**Comment by caiomts** [comment]
Actually it is available as a flag when you stop manually :). Take a look here:  https://github.com/caiomts/timerdo#stop.

**Comment by ardcarvalho** [comment]
Yeah, you're right.
I was just missing the opportunity of not forgeting to add a remark (nothing better as a question before ending the task)
