### ISSUE TITLE
Change in due date (Head of the due list in view mode)

### ISSUE THREAD

**Issue by ardcarvalho** [caiomts/timerdo#8]
The dates in "due date" are different. I've set 2021-12-13, I don't know why the title have changed for 2021-12-14 (I'm quite sure it correctly assigned 2021-12-13 yesterday)... 
ps: this is the only task with a 'due date'
![image](https://user-images.githubusercontent.com/65078687/144995146-d604d9b7-570b-402a-8a92-eae2f1ea4dea.png)

**Comment by caiomts** [comment]
Is this `timerdo view` mode? If yes, have you flagged any due date? Because the normal behavior is to show tasks whose due date is up to a week ahead.

**Comment by ardcarvalho** [comment]
Ahh, ok! Understood.
But isn't better to srite "Due until 2021-12-14"? (if this is a correct english)
